name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Prepare artifacts directory
      run: mkdir -p artifacts

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o ai-editor .
        mv ai-editor artifacts/

    # - name: Build for Windows
    #   run: |
    #     GOOS=windows GOARCH=amd64 go build -o auto-editor.exe .
    #     mv auto-editor.exe artifacts/

    - name: Copy common files
      run: |
        cp config.json artifacts/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
