name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for Linux
      run: |
        # Проверяем структуру проекта (отладка)
        ls -la
        
        # Сборка для Linux (путь нужно уточнить!)
        GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o myapp-linux-arm64 .
        
        mkdir -p artifacts
        mv myapp-linux-* artifacts/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
