name: Build and Release

on:
  push:
    tags:
      - "v*" # Запуск при создании тега (например v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24' # Укажите вашу версию Go

    - name: Build for Linux
      run: |
        # Сборка для Linux (amd64)
        GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64 ./cmd/main
        
        # Опционально: сборка для других архитектур
        GOOS=linux GOARCH=arm64 go build -o myapp-linux-arm64 ./cmd/main
        
        # Создаем папку для артефактов
        mkdir -p artifacts
        mv myapp-linux-* artifacts/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/myapp-linux-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Автоматический токен
