name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install OpenCV dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          libgtk-3-dev \
          pkg-config \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev \
          libtbb12 \          # Вместо libtbb2
          libtbb-dev \
          libjpeg-dev \
          libpng-dev \
          libtiff-dev \
          libdc1394-dev \     # Вместо libdc1394-22-dev
          libopenexr-dev \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer1.0-dev

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build for Linux
      run: |
        # Указываем правильный путь для сборки
        GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64 .
        GOOS=linux GOARCH=arm64 go build -o myapp-linux-arm64 .
        
        mkdir -p artifacts
        mv myapp-linux-* artifacts/

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
